### ISSUE TITLE
Clarrification: does the scoop work like an Ubuntu Snap package?

### ISSUE THREAD

**Issue by luzpaz** [foosel/scoop-bucket#2]
How does the process work?
Does it gets compiled on server and then the user can download via delta (like a snap or an AppImage?)

**Comment by foosel** [comment]
Nothing gets compiled by me here. [scoop](https://scoop.sh) works by having install scripts that allow to fetch precompiled ready to install software from wherever it is hosted and then install it automatically and keep it updated as well for you. 

You might want to check out https://scoop.sh and the [scoop docs](https://github.com/ScoopInstaller/Scoop/wiki) for details.

What you are looking at here is a so called scoop bucket that contains a selected number of install scripts that I wrote for software I need and have shared for easy use by others.
