### ISSUE TITLE
Freecad-linkbranch repo change

### ISSUE THREAD

**Issue by DerekSauer** [foosel/scoop-bucket#3]
Hello,

I have been mooching off your bucket for Freecad-Linkbranch since I could never figure out how to get auto-updating working in my bucket and you did. 

Realthunder has recently moved development of his experimental branch over to https://github.com/realthunder/FreeCAD now that App::Link and Assembly3 are available in mainline. 

Have a good day.

**Comment by foosel** [comment]
Thanks for the heads-up!
